name: Build Proxmox VM

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v14
        with:
          name: jeremiealcaraz
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        run: |
          nix build .#proxmox-vm --show-trace
          mkdir -p out
          echo "Contenu du répertoire result:"
          ls -la result/ || echo "Répertoire result non trouvé"
          echo "Recherche de fichiers .vma ou similaires:"
          find result -type f \( -name "*.vma*" -o -name "*.qcow2" -o -name "*.img" \) 2>/dev/null || echo "Aucun fichier image trouvé"
          echo "Copie du fichier trouvé (s'il existe):"
          # Essaie d'abord .vma.zst, puis les autres formats
          if find result -name "*.vma.zst" -exec cp {} out/nixos.vma.zst \; 2>/dev/null; then
            echo "Fichier .vma.zst copié avec succès"
          elif find result -name "*.vma" -exec cp {} out/nixos.vma.zst \; 2>/dev/null; then
            echo "Fichier .vma copié et renommé en .vma.zst"
          else
            echo "Aucun fichier .vma trouvé à copier"
          fi
          ls -lh out/ || echo "Répertoire out vide"

      - uses: actions/upload-artifact@v4
        with:
          name: nixos-proxmox
          path: out/nixos.vma.zst
