name: Build Proxmox VM

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v14
        with:
          name: jeremiealcaraz
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        run: |
          nix build .#proxmox-vm --show-trace
          mkdir -p out
          
          echo "=== Type de result ==="
          file result || echo "result n'existe pas"
          
          echo "=== Contenu de result (si c'est un répertoire) ==="
          if [ -d result ]; then
            ls -la result/
          fi
          
          echo "=== Si result est un lien symbolique, voir la cible ==="
          if [ -L result ]; then
            readlink result
            TARGET=$(readlink result)
            ls -lh "$TARGET"
          fi
          
          echo "=== Recherche de tous les fichiers .vma* ==="
          find -L result -type f \( -name "*.vma*" -o -name "*.qcow2" \) 2>/dev/null || echo "Aucun fichier trouvé"
          
          echo "=== Copie du fichier ==="
          # nixos-generators avec format proxmox génère un fichier .vma.zst
          # Le fichier est soit directement result, soit dans le store nix
          if [ -f result ]; then
            # result est directement le fichier
            cp result out/nixos.vma.zst
            echo "✓ Fichier result copié directement"
          elif [ -L result ] && [ -f "$(readlink result)" ]; then
            # result est un lien vers le fichier
            cp "$(readlink result)" out/nixos.vma.zst
            echo "✓ Fichier lié copié"
          else
            # Cherche dans result/ si c'est un répertoire
            FOUND_FILE=$(find -L result -type f -name "*.vma.zst" 2>/dev/null | head -n 1)
            if [ -n "$FOUND_FILE" ]; then
              cp "$FOUND_FILE" out/nixos.vma.zst
              echo "✓ Fichier trouvé: $FOUND_FILE"
            else
              echo "✗ Aucun fichier trouvé!"
              ls -laR result/ 2>/dev/null || echo "Impossible de lister result"
              exit 1
            fi
          fi
          
          echo "=== Vérification finale ==="
          ls -lh out/
          file out/nixos.vma.zst

      - uses: actions/upload-artifact@v4
        with:
          name: nixos-proxmox
          path: out/nixos.vma.zst
        if: success()